version: "3"
services:
  mysql:
      image: mysql:8.0

      environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
      ports:
          # <Port exposed> : <MySQL Port running inside container>
          - '3306:3306'
      expose:
          # Opens port 3306 on the container
          - '3306'
          # Where our data will be persisted
      volumes:
          - my-db:/var/lib/mysql

volumes:
      my-db:
